# Generated by Django 6.0.8 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]