# Generated by Django 6.0.7 on 2026-08-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_workflow_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('UI/UX Design', 'UI/UX Design'), ('Graphics Design', 'Graphics Design'), ('Writing', 'Writing'), ('Video Editing', 'Video Editing'), ('Music Production', 'Music Production'), ('Admin & Virtual Assistance', 'Admin & Virtual Assistance'), ('Sales & Lead Generation', 'Sales & Lead Generation'), ('Data & Analytics', 'Data & Analytics'), ('Data Science', 'Data Science'), ('Engineering & Architecture', 'Engineering & Architecture'), ('Business Consulting & Strategy', 'Business Consulting & Strategy'), ('Other', 'Other')], max_length=50),
        ),
    ]
